### PR TITLE
Get rid of the legacy in-house slo framework label

### PR DESCRIPTION
**Pull request by QuentinBisson**
Towards giantswarm/giantswarm#31095

Getting rid of the legacy in-house slo framework

### CODE REVIEW

**Review by AndiDog — APPROVED** [review]

**Comment by fiunchinho** [comment]
@QuentinBisson We are using `vendir` to generate the contents of this app. If you want to change or remove anything from the app, it needs to be removed from the branch of the fork that this app is using. [This app is using branch `release-2.8` of the fork](https://github.com/giantswarm/aws-load-balancer-controller-app/blob/main/vendir.yml#L8-L9), which doesn't have the change. Then you can regenerate the app. You will notice that the `vendir.lock` file would be updated with the new used hash.

**Comment by QuentinBisson** [comment]
Thanks. 

So to be fair, I removed this label for documentation purposes as any thing that uses it will be gone this week or the next and I removed it from the upstream main branch. I would rather not remove it from all versions if that's not really useful work :D

**Comment by fiunchinho** [comment]
The `main` branch is not used at all, just `release-2.8`. I'll do it later today, no worries.

**Comment by QuentinBisson** [comment]
I can remove it from the branch if you want :) I did not know how many you had there :D

**Comment by fiunchinho** [comment]
ok, cool. Thanks :heart:

**Comment by QuentinBisson** [comment]
I think I prefer that you run `vendor sync` because I'm not sure what to do this this change:

```diff
-version: 2.1.0
+version: 1.8.3
```

But I removed the label in the release-2.8 branch in the upstream repo

**Comment by fiunchinho** [comment]
ok, I'll take care of it. Thanks!

**Pull request merged**
